### ISSUE TITLE
Ability to insert native source nodes in the pipeline

### ISSUE THREAD

**Issue by youennf** [w3c/webrtc-insertable-streams#17]
end-to-end encryption is one node that would be best implemented natively.
There are several benefits:
1. Implementation of a single standardised format, widely studied, widely tested, well maintained
2. An API to provide the key material to the encryption node. This API can be extended to support different trust models
3. The ability to not expose encryption keys to the JS (directly or through attacks like Spectre)

**Comment by youennf** [comment]
Another possible extension would be a node allowing to send some synchronized metadata along the encoded video packets.

**Comment by alvestrand** [comment]
I think this is extremely simple in the worker model:

const standardWorker = new Worker("urn:w3c:standardized-function-234");

This would create a worker with an API specified by a standard, and implemented in the browser.
Its messaging interface could be used to execute the key exchange protocol's message passing, in the same way as SetLocalDescription() and friends execute the offer/answer exchange for PeerConnections.

**Comment by youennf** [comment]
Maybe that could work.
This means that you would implement the specific API of the node through postMessage, right? If so, this feels a bit strange to me.
It might not be that much more difficult to specify and implement a native node with a proper native API.

**Comment by youennf** [comment]
Thinking about it more, I do not think a worker is the best approach with the current design.
Instead, a native processing node could be modelled as a transform stream whose transform processing is natively implemented.

**Comment by youennf** [comment]
This is similar to https://wicg.github.io/compression/#compression-stream.

**Comment by alvestrand** [comment]
I think the two approaches are equivalent; which one is preferred by a spec writer depends on whether he/she is more comfortable writing IDL specifications (like CompressionStream) or message specifications (like a standardized worker).

**Comment by youennf** [comment]
I would look at what would be most convenient and easy to understand by a web developer.
Also, a usual expectation is one worker = one thread in terms of implementation (and at least my mental model), which is not the case with a transform stream.

**Comment by murillo128** [comment]
note that you will need to handle more than one stream pair, so if we go for the native transform stream objects, there must be a higher level objects that creates/coordinates them and performs all the key handling.

**Comment by youennf** [comment]
Fixed by https://github.com/w3c/webrtc-insertable-streams/pull/51
