### ISSUE TITLE
Does Chromium require anything in SDP or RTP Header to make this work?

### ISSUE THREAD

**Issue by Sean-Der** [w3c/webrtc-insertable-streams#37]
Sorry to talk about this on W3C repo, but I have no idea how to contact any Chrome developers.

I tried to code up an example [here](https://github.com/pion/webrtc/pull/1252/files) but hitting weird behavior. After processing my buffers I get the right values (the values I sent), but the browser fails to decode them. In the debug logs I just get `Failed to decode frame with timestamp 2656706362, error code: -1`

I am not that familiar with the Chromium code base, but do you know if this feature depends on anything else? I see lots of extmap entries and multiple RTP headers, hoping this is behind something I haven't found yet.

Will keep debugging, going to send both tracks in and diff each packet and see if I am making a mistake here. Can't find anything yet though.

thanks

**Comment by guidou** [comment]
In some cases you may need to enable the GFD extension.
Currently, you can do that on the command line or by munging SDP.

Command line:
--force-fieldtrials=WebRTC-GenericDescriptorAdvertised/Enabled

For a possible munging, see: https://cs.chromium.org/chromium/src/third_party/blink/web_tests/fast/peerconnection/RTCPeerConnection-insertable-streams.js?q=insertable-streams.js&sq=package:chromium&dr&l=57

A Web Platform API is proposed to make it easier to control RTP Header extensions:
https://w3c.github.io/webrtc-extensions/

**Comment by murillo128** [comment]
I would recommend you to start with the audio stream as it is easier to get it working.

For video, either you would have to implement the generic raw paquetization and generic video description rtp extension header, or you would need to adapt the encryption per codec.

If you do the later, VP9 will work out of the box, VP8 would require to skip the first 3/10 bytes of the vp8 descriptor and for h264, well, better do the generic paquetizer/descriptor.

If you want to integrate it wit the [sframe.js](https://github.com/medooze/sframe) on the browser side, contact me privately and I will help you to interoperate with it.

**Comment by Sean-Der** [comment]
@guidou thanks for the help! 

So I am trying to send into Chromium for another agent. Do you know what I need to implement as a minimum to get this working? I am not using libwebrtc at all, so need to figure out stuff at the protocol level.

----

@murillo128 So I don't fully understand how this all ties together, here are my naive questions :)

* This API is just giving access to the RTP Payloads?
* Why does it need to be codec aware? If I just want to do a simple XOR across all the bytes on each side, does it matter?
* How/why do those RTP extension headers come into play? Is there more logic then just handling the SSRC/PayloadType? 


I haven't had a chance to fully grok sframe yet, I assumed `Insertable Streams` was just a matter of giving a callback to users so they could flip bytes around in the Payload.

**Comment by murillo128** [comment]
The encryption is done on full media frames, just after the encoder and before the rtp packetization. So the rtp packetization won't work on the ecnrypted frames if your encryption is not codec packetization aware or if you don't use the generic rtp packetization which is codec agnostic.

**Comment by Sean-Der** [comment]
Oh I see!

So my VP8 packetization [here](https://github.com/pion/rtp/blob/master/codecs/vp8_packet.go#L14) is really simple. I just set the `S` bit, I don't care about anything else. This has been working in Chromium so far (pre Insertable Streams)

But it sounds like when you enable `Insertable Streams` new logic is happening (Generic RTP Packetization)(?) I haven't found the RFC with this yet, not familiar with this at all :/

So far I have tried just sending into the browser, and was encrypting after (before) packetization. I will work on implementing generic rtp packetization. Thank you so much @murillo128 !

**Comment by murillo128** [comment]
No, there is no new logic happening if insertable streams is used, but as I said before, it won't work if you are not using the new generic rtp packetization and header extensions or if you are not taking the codec specific packetization when doing the crypto.

Note that for vp8 that means skiping the first 3/10 bytes (depending of the frame type) of the media frame payload (the frame header in https://tools.ietf.org/html/rfc6386#page-30) which I think is skiping the first bits of your `payload` in here:

https://github.com/pion/rtp/blob/master/codecs/vp8_packet.go#L39

**Comment by Sean-Der** [comment]
@murillo128 Is [rtp_generic_frame_descriptor_extension.cc](https://source.chromium.org/chromium/chromium/src/+/master:third_party/webrtc/modules/rtp_rtcp/source/rtp_generic_frame_descriptor_extension.cc;l=33) defined anywhere? If you had a few example packets would really make this easier :)

Has http://www.webrtc.org/experiments/rtp-hdrext/generic-frame-descriptor-00 been shared elsewhere?

So if I set this properly I should just expect everything in the Payload after the GFD?

Thanks for answering all the questions on this. Amazing how much is going on that I completely oblivious of :/

**Comment by Sean-Der** [comment]
@murillo128 @guidou @SourceCodeZone @agouaillard Figured it out!

It had nothing to do with anything discussed in the issue, this is just an issue in the browser.When using a XOR Cipher with a cipherKey of `0xAB` causes video decode failures. If I use `0xAA` it works.

https://jsfiddle.net/zmwo640s/ In the JS try change `CIPHER_KEY` to `0xAB`. There is probably some rule to Javascript I am missing here.

**Comment by murillo128** [comment]
> @murillo128 @guidou @SourceCodeZone @agouaillard Figured it out!
> 
> It had nothing to do with anything discussed in the issue, this is just an issue in the browser. When using a XOR Cipher with a cipherKey of `0xAB` it causes video decode failures. If I use `0xAA` it works. My code from two days ago works I just need to change `0xAB` => `0xAA` 
> 
> https://jsfiddle.net/zmwo640s/ In the JS try change `CIPHER_KEY` to `0xAB`. There is probably some rule to Javascript I am missing here.
> 
> Also huge shout out to @murillo128 and @guidou, this has been one of the best interactions in Open Source I have had in a while. Thank you so much for taking your time to answer my questions (no matter how stupid they are). Hopefully stuff like this convinces others it is possible to have a community like that :)

You are not skipping the first 3 or 10 bytes of the vp8 frame, and as you are not using the generic paquetizer/descriptor that changes the vp8 descriptor which is used by chrome for packetization and everything is broken.

Changing from 0xAB to 0xAA probably just keep some bits intact after encryption that made it work just by pure luck.

**Comment by Sean-Der** [comment]
Oh I completely missed your original point.

I thought that the header was having issues on reception, but it is Chrome's outbound packetization that I was breaking. Was focusing on the wrong thing.

Should I make a PR against the `webrtc-samples` repo? [endtoend-encryption](https://github.com/webrtc/samples/blob/gh-pages/src/content/peerconnection/endtoend-encryption/js/worker.js#L117) will sometimes encrypt the header. I don't see it explicitly enabling GFD either.

----

Unrelated, but why is GFD a requirement for this? Chrome will have to generate/capture metadata to generate the plaintext GFD and prepend it. Why not generate the payload specific header before the insertable stream as well?

**Comment by asineth0** [comment]
Anyone know how to get this working with H264? I have it working with VP8 & Opus packets by keeping the first 3/10/1 bytes. I am doing this for a native desktop app, so if I need to add commandline arguments or do SDP munging that's fine.

**Comment by alexivaner** [comment]
Anyone, manage it working with H264? in my case I could not decode encrypted frame from H264, I already skip 12 first payload, and log all the payload. The payload can decrypt properly and back to the original before decrypted, but the video sometimes remains black with a bit of pixelated square. This is works fine on VP8, so I wonder what's wrong with H264.

**Comment by fippo** [comment]
Probably caused by https://issues.webrtc.org/issues/42222006
It seems I had a WIP branch for the samples but did not push it: https://github.com/fippo/webrtc/tree/h264-mimetype
