### ISSUE TITLE
https://alvestrand.github.io/webrtc-media-streams/ is 404

### ISSUE THREAD

**Issue by guest271314** [w3c/webrtc-insertable-streams#42]
https://alvestrand.github.io/webrtc-media-streams/ is 404

**Comment by guest271314** [comment]
Not sure what is happening. Fork of master is different than current master?

**Comment by guidou** [comment]
moved to w3c.

**Comment by guest271314** [comment]
@guidou While you are around have two questions and not sure where to post them, WebRTC and/or Media Capture and Streams. Have created a workaround for https://bugs.chromium.org/p/chromium/issues/detail?id=1013881 and https://bugs.chromium.org/p/chromium/issues/detail?id=931749 that achieves the expected result at localhost, however to complete the requirement the code needs to be usable at any URL. Am not certain exactly about the signaling flow-chart of WebRTC, or if filing a feature request at Insertable Streams, WebRTC, or Media Capture and Streams is the correct way to proceed. Where to ask such questions? Thanks.
